// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_eg439.Models;

namespace Mission6_eg439.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_eg439.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "SciFi"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Musical"
                        });
                });

            modelBuilder.Entity("Mission6_eg439.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Director = "Your Mom",
                            Edited = true,
                            Rating = "PG-13",
                            Title = "Fast and Furious",
                            Year = "1999"
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1,
                            Director = "Your Dad",
                            Edited = false,
                            Notes = "This is possibly the best movie ever created",
                            Rating = "PG-13",
                            Title = "Avatar",
                            Year = "2011"
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 3,
                            Director = "Your Dad",
                            Edited = false,
                            Notes = "This is another one of the greatest films every made",
                            Rating = "PG",
                            Title = "Cinderlla Story: Hillary Duff",
                            Year = "2011"
                        });
                });

            modelBuilder.Entity("Mission6_eg439.Models.Movie", b =>
                {
                    b.HasOne("Mission6_eg439.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
